x-common-variables: &common-variables
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_DB: ${POSTGRES_DB}

services:
  db:
    image: ankane/pgvector
    environment:
      <<: *common-variables
    ports:
      - "5432:5432"

  app:
    image: rag_test
    build: .
    command: uvicorn rag_test.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./resources:/app/resources
    environment:
      <<: *common-variables
      INITIAL_DATA_PATH: '/app/resources/recipes'
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      POSTGRES_HOST: db
